import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, View, useWindowDimensions } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useGame } from '@/src/game/GameContext';
import { api, Order } from '@/src/game/api';
import { distance, gameTime, getRoute } from '@/src/game/world';
import { makeStyles, useTheme } from '@/src/theme';
import { Button, Coin, Icon, Label } from './ui';
import { BikeArt } from './BikeArt';
import { MiniMap } from './CityWorld';

function OrderView() {
  const g = useGame(); const s = useStyles(); const { colors: c } = useTheme(); const o = g.order;
  if (!o) return <View testID="phone-no-orders" style={s.empty}><View style={s.emptyArt}><BikeArt width={175} height={112} /></View><Label display style={s.emptyTitle}>{g.profile!.online ? 'Your next little adventure.' : 'A little break is good.'}</Label><Label style={s.emptyText}>{g.profile!.online ? 'The city has places to go and people to make smile. Check for a fresh delivery.' : 'You’re offline. Go online whenever you’re ready to pick up a delivery.'}</Label><Button testID="phone-go-online-button" title={g.profile!.online ? 'CHECK FOR ORDERS' : 'GO ONLINE'} onPress={g.profile!.online ? () => g.refreshOrder().catch(e => g.notify(e.message)) : g.toggleOnline} loading={g.busy} icon="power" /></View>;
  const offered = o.status === 'offered', collecting = o.status === 'accepted';
  const target = collecting ? o.pickup : o.dropoff;
  const near = !offered && distance(g.position.current, target) < 62;
  return <View testID="phone-order-detail">
    <View style={s.orderHeading}><View><Label style={s.eyebrow}>{offered ? 'FRESH OFF THE PRESS' : collecting ? 'LET’S PICK IT UP' : 'ON THE HOME STRETCH'}</Label><Label display style={s.orderTitle}>{offered ? 'A good day to deliver.' : collecting ? 'Good things are waiting.' : 'One happy customer.'}</Label></View></View>
    <View style={s.orderReward}><View style={s.deliveryIcon}><Icon name="bag-handle-outline" size={28} /></View><View style={s.orderRewardCopy}><Label style={s.orderItem}>{o.item}</Label><Label style={s.orderItemSub}>A little something for {o.customer}</Label></View><Coin amount={`+${o.reward}`} /></View>
    <View style={s.routeCard}>
      <View style={s.stop}><View style={[s.stopIcon, collecting && s.activeStop]}><Icon name={o.status === 'picked_up' ? 'checkmark' : 'storefront-outline'} size={20} color={c.teal} /></View><View style={s.stopCopy}><Label style={s.stopLabel}>{o.status === 'picked_up' ? 'COLLECTED' : 'PICK UP FROM'}</Label><Label style={s.stopName}>{o.pickup.name}</Label><Label style={s.stopAddress}>{o.pickup.address}</Label></View></View>
      <View style={s.routeConnector}><View style={s.connectorLine} /><Label style={s.routeDistance}>{Math.round(distance(o.pickup, o.dropoff))} m across the neighborhood</Label></View>
      <View style={s.stop}><View style={[s.stopIcon, o.status === 'picked_up' && s.activeStop]}><Icon name="location-outline" size={21} color={c.teal} /></View><View style={s.stopCopy}><Label style={s.stopLabel}>DELIVER TO</Label><Label style={s.stopName}>{o.dropoff.name}</Label><Label style={s.stopAddress}>{o.customer} · {o.dropoff.address}</Label></View></View>
    </View>
    <View style={s.promise}><Icon name="heart-outline" color={c.teal} size={17} /><Label style={s.promiseText}>No ticking clock. Just a lovely little ride.</Label></View>
    {offered ? <><Button testID="accept-order-button" title="ACCEPT DELIVERY" onPress={g.accept} loading={g.busy} icon="arrow-forward" /><Pressable testID="decline-order-button" onPress={g.decline} disabled={g.busy} style={s.textButton}><Label style={s.textButtonLabel}>Not this one</Label></Pressable></> : <><Button testID="phone-continue-delivery-button" title={near ? collecting ? 'PICK UP ORDER' : 'DELIVER ORDER' : 'BACK TO THE STREETS'} onPress={near ? g.interact : () => { g.setPhone(false); if (g.screen === 'garage') g.headOut(); }} loading={g.busy} icon={near ? 'bag-check-outline' : 'navigate-outline'} /><Pressable testID="cancel-order-button" onPress={g.decline} disabled={g.busy} style={s.textButton}><Label style={s.textButtonLabel}>Cancel this delivery</Label></Pressable></>}
  </View>;
}
function WalletView() {
  const g = useGame(); const s = useStyles(); const { colors: c } = useTheme();
  const [history, setHistory] = useState<Order[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const load = () => { setLoading(true); setError(''); api<Order[]>('/orders/history').then(setHistory).catch(e => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(load, []);
  return <View testID="wallet-screen"><Label style={s.eyebrow}>LITTLE RIDES ADD UP</Label><Label display style={s.orderTitle}>Your pocket of sunshine.</Label><View style={s.balanceCard}><Label style={s.balanceLabel}>YOUR BALANCE</Label><View style={s.bigBalance}><Coin amount={g.profile!.balance} /><Label style={s.coinCaption}>coins</Label></View><View style={s.balanceRule} /><View style={s.walletStats}><View><Label display style={s.statValue}>{g.profile!.deliveries}</Label><Label style={s.statCaption}>Happy deliveries</Label></View><View><Label display style={s.statValue}>{g.profile!.earned}</Label><Label style={s.statCaption}>Lifetime coins</Label></View><View><Label display style={s.statValue}>{g.profile!.xp}</Label><Label style={s.statCaption}>Total XP</Label></View></View></View><Label display style={s.historyTitle}>The delivery journal</Label>{loading ? <ActivityIndicator color={c.teal} style={{ margin: 20 }} /> : error ? <><Label style={s.emptyText}>{error}</Label><Button testID="wallet-retry-button" title="TRY AGAIN" onPress={load} secondary /></> : history.length ? history.map(o => <View testID={`delivery-history-${o.id}`} key={o.id} style={s.historyRow}><View style={s.historyIcon}><Icon name="checkmark" color={c.teal} size={20} /></View><View style={s.historyCopy}><Label style={s.historyName}>{o.pickup.name}</Label><Label style={s.historySub}>Delivered to {o.customer} · +{o.xp} XP</Label></View><Coin amount={`+${o.reward}`} small /></View>) : <View style={s.journalEmpty}><Icon name="book-outline" size={30} color={c.teal} /><Label style={s.emptyText}>Your story starts with your first delivery.{ '\n' }We’ll keep the good days here.</Label></View>}<View style={s.promise}><Icon name="sparkles-outline" color={c.teal} size={18} /><Label style={s.promiseText}>Earn coins to upgrade your ride back in the garage.</Label></View></View>;
}
function GPSView() {
  const g = useGame(); const s = useStyles(); const { colors: c } = useTheme(); const { width } = useWindowDimensions();
  const target = g.order?.status === 'accepted' ? g.order.pickup : g.order?.status === 'picked_up' ? g.order.dropoff : null;
  return <View><Label style={s.eyebrow}>A SMALL CITY. ENDLESS LITTLE STORIES.</Label><Label display style={s.orderTitle}>Hello, Sunnyvale.</Label><View style={s.largeMap}><MiniMap large player={g.position.current} target={target} route={target ? getRoute(g.position.current, target) : []} size={Math.min(width - 108, 320)} /></View><View style={s.mapLegend}><View style={s.legendItem}><View style={s.riderDot} /><Label style={s.legendLabel}>You are here</Label></View><View style={s.legendItem}><View style={s.targetDot} /><Label style={s.legendLabel}>Your destination</Label></View></View><View style={s.destination}><Icon name="navigate-outline" color={c.teal} /><View style={{ flex: 1 }}><Label style={s.stopName}>{target ? target.name : 'Take the scenic route'}</Label><Label style={s.stopAddress}>{target ? target.address : 'Accept an order to get turn-by-turn directions.'}</Label></View></View><Button testID="gps-back-to-ride-button" title={g.screen === 'garage' ? 'HEAD OUT & EXPLORE' : 'BACK TO THE RIDE'} onPress={() => { g.setPhone(false); if (g.screen === 'garage') g.headOut(); }} icon="arrow-forward" /></View>;
}
export function Phone() {
  const g = useGame(); const s = useStyles(); const { height, width } = useWindowDimensions(); const inset = useSafeAreaInsets();
  const tabs = [{ id: 'orders', label: 'Orders', icon: 'bag-handle-outline' }, { id: 'gps', label: 'GPS', icon: 'navigate-outline' }, { id: 'wallet', label: 'Wallet', icon: 'wallet-outline' }] as const;
  return <View testID="phone-modal" style={[s.phone, { width: Math.min(width - 40, 420), height: Math.min(height - inset.top - inset.bottom - 64, 730) }]}>
    <View style={s.phoneTop}><Label style={s.phoneTime}>{gameTime(g.clock.current)}</Label><View style={s.speaker} /><View style={s.signal}><Icon name="cellular" size={13} /><Icon name="battery-full" size={17} /></View></View>
    <View style={s.phoneHeader}><View><Label display style={s.phoneBrand}>dash<Label style={s.phoneBrandDot}>.</Label></Label><Label style={s.phoneTagline}>Good things, delivered.</Label></View><Pressable testID="phone-close-button" accessibilityLabel="Close phone" onPress={() => g.setPhone(false)} style={s.close}><Icon name="close" /></Pressable></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} style={s.tabs} contentContainerStyle={s.tabContent}>{tabs.map(tab => <Pressable testID={`phone-tab-${tab.id}`} key={tab.id} accessibilityState={{ selected: g.phoneTab === tab.id }} onPress={() => g.setPhoneTab(tab.id)} style={[s.tab, g.phoneTab === tab.id && s.tabActive]}><Icon name={tab.icon} size={16} /><Label style={s.tabLabel}>{tab.label}</Label></Pressable>)}</ScrollView>
    <ScrollView testID="phone-content-scroll" style={s.phoneScroll} showsVerticalScrollIndicator={false} contentContainerStyle={s.phoneContent}>{g.phoneTab === 'orders' ? <OrderView /> : g.phoneTab === 'wallet' ? <WalletView /> : <GPSView />}</ScrollView>
    <View style={s.phoneBottom}><Pressable testID="phone-online-toggle" onPress={g.toggleOnline} disabled={g.busy} style={s.phoneStatus}><View style={[s.statusDot, !g.profile!.online && s.offlineDot]} /><Label style={s.phoneStatusText}>{g.profile!.online ? 'You’re online · taking deliveries' : 'You’re offline · taking it easy'}</Label><Icon name="power" size={14} /></Pressable><View style={s.homeBar} /></View>
  </View>;
}
const useStyles = makeStyles(c => ({
  phone: { borderWidth: 7, borderColor: c.onSurface, backgroundColor: c.surface, borderRadius: 40, overflow: 'hidden', alignSelf: 'center', shadowColor: c.onSurface, shadowOffset: { width: 0, height: 18 }, shadowOpacity: .3, shadowRadius: 24 }, phoneTop: { height: 29, paddingHorizontal: 21, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, phoneTime: { fontSize: 9, fontWeight: '800' }, speaker: { height: 7, width: 64, backgroundColor: c.onSurface, borderRadius: 5 }, signal: { flexDirection: 'row', gap: 3, alignItems: 'center' }, phoneHeader: { paddingHorizontal: 20, paddingTop: 9, paddingBottom: 9, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, phoneBrand: { fontSize: 31, letterSpacing: -1 }, phoneBrandDot: { color: c.teal, fontSize: 31 }, phoneTagline: { fontSize: 9, color: c.muted }, close: { height: 44, width: 44, borderRadius: 22, backgroundColor: c.surfaceTertiary, alignItems: 'center', justifyContent: 'center' },
  tabs: { height: 56, maxHeight: 56, flexGrow: 0, borderBottomWidth: 1, borderColor: c.border }, tabContent: { paddingHorizontal: 18, gap: 8, alignItems: 'center' }, tab: { flexShrink: 0, height: 36, paddingHorizontal: 16, flexDirection: 'row', gap: 6, borderRadius: 11, alignItems: 'center', borderWidth: 1, borderColor: c.border, backgroundColor: c.surface }, tabActive: { backgroundColor: c.brand, borderColor: c.onSurface }, tabLabel: { fontSize: 11, fontWeight: '800' }, phoneScroll: { flex: 1 }, phoneContent: { padding: 18, paddingTop: 22, paddingBottom: 12 },
  phoneBottom: { borderTopWidth: 1, borderColor: c.border, paddingHorizontal: 16, paddingBottom: 9 }, phoneStatus: { minHeight: 44, flexDirection: 'row', gap: 7, alignItems: 'center', justifyContent: 'center' }, statusDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: c.success }, offlineDot: { backgroundColor: c.muted }, phoneStatusText: { fontSize: 10, color: c.muted }, homeBar: { alignSelf: 'center', width: 100, height: 4, backgroundColor: c.onSurface, borderRadius: 4 },
  eyebrow: { fontSize: 8, color: c.teal, letterSpacing: 1.2, fontWeight: '800', marginBottom: 6 }, orderHeading: { marginBottom: 18 }, orderTitle: { fontSize: 23, letterSpacing: -.5, marginBottom: 5 }, orderReward: { flexDirection: 'row', gap: 10, alignItems: 'center', marginBottom: 18 }, deliveryIcon: { width: 43, height: 48, borderRadius: 13, backgroundColor: c.butter, justifyContent: 'center', alignItems: 'center' }, orderRewardCopy: { flex: 1 }, orderItem: { fontSize: 12, fontWeight: '800' }, orderItemSub: { fontSize: 9, color: c.muted, marginTop: 4 }, routeCard: { padding: 15, borderWidth: 1, borderColor: c.border, borderRadius: 17, backgroundColor: c.surfaceSecondary }, stop: { flexDirection: 'row', alignItems: 'center', gap: 11 }, stopIcon: { width: 35, height: 38, borderRadius: 11, backgroundColor: c.mint, alignItems: 'center', justifyContent: 'center' }, activeStop: { backgroundColor: c.butter }, stopCopy: { flex: 1 }, stopLabel: { fontSize: 7, fontWeight: '800', letterSpacing: 1.1, color: c.teal, marginBottom: 4 }, stopName: { fontSize: 12, fontWeight: '800' }, stopAddress: { fontSize: 9, color: c.muted, marginTop: 4 }, routeConnector: { height: 37, flexDirection: 'row', gap: 26, paddingLeft: 17, alignItems: 'center' }, connectorLine: { height: 24, width: 1, backgroundColor: c.border }, routeDistance: { fontSize: 8, color: c.muted }, promise: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 16 }, promiseText: { fontSize: 10, color: c.teal, flex: 1 }, textButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center' }, textButtonLabel: { fontSize: 11, color: c.muted, textDecorationLine: 'underline' },
  empty: { paddingVertical: 14 }, emptyArt: { backgroundColor: c.butter, width: 178, height: 148, borderRadius: 80, alignItems: 'center', justifyContent: 'center', alignSelf: 'center', marginBottom: 23 }, emptyTitle: { fontSize: 25, textAlign: 'center' }, emptyText: { fontSize: 12, lineHeight: 20, color: c.muted, textAlign: 'center', marginTop: 12, marginBottom: 24 }, balanceCard: { backgroundColor: c.brand, borderRadius: 20, borderWidth: 1.5, borderBottomWidth: 4, borderColor: c.onSurface, padding: 19, marginTop: 18 }, balanceLabel: { fontSize: 8, letterSpacing: 1.4, fontWeight: '800' }, bigBalance: { flexDirection: 'row', alignItems: 'baseline', gap: 8, marginTop: 12 }, coinCaption: { fontSize: 13 }, balanceRule: { height: 1, backgroundColor: c.onSurface, opacity: .15, marginVertical: 18 }, walletStats: { flexDirection: 'row', justifyContent: 'space-between' }, statValue: { fontSize: 23 }, statCaption: { fontSize: 8, marginTop: 3 }, historyTitle: { fontSize: 20, marginTop: 24, marginBottom: 14 }, historyRow: { flexDirection: 'row', gap: 9, alignItems: 'center', paddingVertical: 13, borderBottomWidth: 1, borderColor: c.border }, historyIcon: { width: 33, height: 33, borderRadius: 11, backgroundColor: c.mint, alignItems: 'center', justifyContent: 'center' }, historyCopy: { flex: 1 }, historyName: { fontSize: 11, fontWeight: '800' }, historySub: { fontSize: 9, color: c.muted, marginTop: 4 }, journalEmpty: { alignItems: 'center', paddingTop: 17 }, largeMap: { marginTop: 14, borderRadius: 17, overflow: 'hidden', borderWidth: 1.5, borderColor: c.borderStrong, alignItems: 'center', backgroundColor: c.grass }, mapLegend: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 12 }, legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 }, riderDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: c.teal }, targetDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: c.brand }, legendLabel: { fontSize: 9, color: c.muted }, destination: { flexDirection: 'row', gap: 9, alignItems: 'center', paddingBottom: 20, paddingTop: 6 },
}));