import React, { useState } from 'react';
import { View } from 'react-native';
import { makeStyles, useTheme } from '@/src/theme';
import { useGame } from '@/src/game/GameContext';
import { Button, Icon, Label } from './ui';

export function StatusPanel() {
  const g = useGame(), s = useStyles(), { colors: c } = useTheme();
  return <View testID="online-status-instructions"><View style={s.art}><Icon name="phone-portrait-outline" size={53} color={c.teal} /></View><Label display style={s.title}>Your phone runs the show.</Label><Label style={s.body}>You’re currently {g.profile!.online ? 'online' : 'offline'}. To change this, open your phone and tap the online/offline switch at the bottom. This indicator only shows your status.</Label><Button testID="status-open-phone-button" title="OPEN MY PHONE" icon="phone-portrait-outline" onPress={() => g.openPhone()} /></View>;
}
export function ServicePanel() {
  const g = useGame(), s = useStyles(), { colors: c } = useTheme(), stop = g.serviceStop!, p = g.profile!, stats = p.bikes[p.bike];
  return <View testID="service-stop-detail"><View style={s.art}><Icon name={stop.kind === 'repair' ? 'construct-outline' : stop.kind === 'garage' ? 'home-outline' : 'water-outline'} size={53} color={c.teal} /></View><Label style={s.kicker}>A PIT STOP, NOT A SETBACK</Label><Label display style={s.title}>{stop.name}</Label><Label style={s.body}>{stop.address}</Label>{stop.kind === 'garage' ? <><Label style={s.body}>Rest at home for free. Restore health and energy, and grab a small pantry snack if you’re hungry. Your bike still needs fuel and professional repairs.</Label><Button testID="service-enter-garage-button" title="GO HOME & REST" onPress={g.returnGarage} loading={g.busy} /></> : stop.kind === 'repair' ? <><Label style={s.body}>Bike condition: {Math.ceil(stats.condition)}%. A full repair costs {Math.max(2, Math.ceil((100 - stats.condition) * .25))} coins.</Label><Button testID="service-repair-button" title="PAY & REPAIR BIKE" onPress={() => g.useService('repair')} disabled={stats.condition >= 99.9} loading={g.busy} /></> : <><Label style={s.body}>{p.bike === 'bicycle' ? `Tire air: ${Math.ceil(stats.air)}%. Fill your bicycle tires for 4 coins.` : `Fuel: ${Math.ceil(stats.fuel)}%. Fill your tank for 12 coins.`}</Label><Button testID="service-refill-button" title={p.bike === 'bicycle' ? 'PUMP TIRES · 4 COINS' : 'REFUEL · 12 COINS'} onPress={() => g.useService(p.bike === 'bicycle' ? 'pump' : 'refuel')} disabled={(p.bike === 'bicycle' ? stats.air : stats.fuel) >= 99.9} loading={g.busy} /></>}<Label style={s.body}>Your balance: {p.balance} coins</Label></View>;
}
export function RecoveryPanel() {
  const g = useGame(), s = useStyles(), { colors: c } = useTheme(); const [confirm, setConfirm] = useState(false);
  return <View testID="death-recovery-modal" style={s.recovery}><View style={s.art}><Icon name="heart-dislike-outline" size={55} color={c.coral} /></View><Label style={s.kicker}>YOUR HEALTH REACHED ZERO</Label><Label display style={s.title}>{confirm ? 'Start from zero?' : 'The ride ends here… for now.'}</Label><Label style={s.body}>{confirm ? 'This erases your coins, deliveries, milestones, food and upgrades. You will restart at the garage with the starter bikes and supplies.' : 'Your active order is cancelled. Pay 15 coins to recover at your garage and keep your progress. If you cannot or choose not to pay, restart from zero.'}</Label>{confirm ? <><Button testID="confirm-restart-button" title="ERASE SAVE & RESTART" onPress={() => g.recover('restart')} loading={g.busy} /><Button testID="cancel-restart-button" title="GO BACK" secondary onPress={() => setConfirm(false)} style={{ marginTop: 12 }} /></> : <><Button testID="pay-recovery-button" title="RECOVER · 15 COINS" onPress={() => g.recover('pay')} disabled={g.profile!.balance < 15} loading={g.busy} /><Label style={s.body}>You have {g.profile!.balance} coins.{g.profile!.balance < 15 ? ' Not enough for recovery.' : ''}</Label><Button testID="restart-choice-button" title="RESTART FROM ZERO" secondary onPress={() => setConfirm(true)} /></>}</View>;
}
const useStyles = makeStyles(c => ({ art: { width: 104, height: 104, borderRadius: 52, alignItems: 'center', justifyContent: 'center', backgroundColor: c.mint, alignSelf: 'center', marginBottom: 23 }, title: { fontSize: 28, marginBottom: 12 }, kicker: { fontSize: 9, letterSpacing: 1.2, color: c.teal, fontWeight: '800', marginBottom: 10 }, body: { fontSize: 13, lineHeight: 21, color: c.muted, marginBottom: 20, marginTop: 8 }, recovery: { backgroundColor: c.surface, padding: 26, borderRadius: 28, width: '90%', maxWidth: 410, borderWidth: 2, borderBottomWidth: 5, borderColor: c.onSurface } }));