import React from 'react';
import { Pressable, View, useWindowDimensions } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { makeStyles, useTheme } from '@/src/theme';
import { useGame } from '@/src/game/GameContext';
import { useRide } from '@/src/game/useRide';
import { countdown, distance, gameTime, getRoute, onFootpath, region } from '@/src/game/world';
import { CityWorld, MiniMap } from '@/src/components/CityWorld';
import { RideControls } from '@/src/components/RideControls';
import { Button, Icon, IconButton, Label } from '@/src/components/ui';
import { RideStatus } from '@/src/components/RideStatus';

export function City() {
  const g = useGame(); const ride = useRide(); const s = useStyles(); const { colors: c } = useTheme();
  const { width, height } = useWindowDimensions(); const inset = useSafeAreaInsets();
  const orderTarget = g.order?.status === 'accepted' ? g.order.pickup : g.order?.status === 'picked_up' ? g.order.dropoff : null;
  const target = g.destination || orderTarget;
  const exploring=g.destination&&!['garage','fuel','repair'].includes(g.destination.kind);
  const route = target ? getRoute(ride.player, target) : [];
  const remaining = route.reduce((sum, p, i) => sum + (i ? distance(p, route[i - 1]) : 0), 0);
  const near = orderTarget && distance(ride.player, orderTarget) <= 35 && onFootpath(ride.player);
  const nearService = g.catalog!.services.find(stop => distance(ride.player, stop) < 37 && onFootpath(ride.player));
  const targetNear = target && distance(ride.player, target) <= 35 && onFootpath(ride.player);
  const next = route.find((p, i) => i > 0 && distance(p, ride.player) > 18) || target;
  const north = next && Math.abs(next.y - ride.player.y) > Math.abs(next.x - ride.player.x);
  const nextDirection = next ? north ? next.y < ride.player.y ? 'north' : 'south' : next.x < ride.player.x ? 'west' : 'east' : '';
  return <View testID="city-screen" style={s.page}>
    <CityWorld {...ride} route={route} target={target} width={width} height={height} bike={g.profile!.bike} gear={g.profile!.gear} />
    <View pointerEvents="box-none" style={[s.top, { top: inset.top + 14 }]}>
      <View style={s.topRow}><IconButton testID="ride-pause-button" name="grid-outline" label="Pause ride" onPress={() => g.setPanel('pause')} style={s.home} /><Pressable testID="world-settings-button" onPress={() => g.setPanel('world')} style={s.weather}><Icon name={ride.weather === 'rainy' ? 'rainy-outline' : ride.weather === 'cloudy' ? 'cloud-outline' : ride.minutes >= 1140 || ride.minutes < 360 ? 'moon-outline' : 'sunny-outline'} size={18} /><Label testID="game-clock" style={s.clock}>{gameTime(ride.minutes)}</Label><View style={s.smallDivider} /><Label testID="game-weather" style={s.weatherLabel}>{ride.weather}</Label></Pressable><Pressable testID="online-status-button" onPress={() => g.setPanel('status')} style={[s.status, g.profile!.online && s.onlineActive]}><View style={[s.onlineDot, { backgroundColor: g.profile!.online ? c.success : c.muted }]} /><Label testID="online-status" style={s.onlineText}>{g.profile!.online ? 'ONLINE' : 'OFFLINE'}</Label></Pressable></View>
      <View style={s.mapRow} pointerEvents="box-none">
        <Pressable testID="open-gps-button" onPress={() => g.openPhone('gps')} style={s.map}><View style={s.mapWindow}><MiniMap player={ride.player} target={target} route={route} size={100} /></View><View style={s.mapLabel}><Icon name="navigate" size={11} color={c.teal} /><Label testID="current-region" style={s.mapText}>{region(ride.player).toUpperCase()}</Label><Icon name="expand" size={10} /></View></Pressable>
        <View style={s.rightTop}><RideStatus /></View>
      </View>
      {g.order?.status === 'offered' && <Pressable testID="new-order-notification" onPress={() => g.openPhone('orders')} style={s.notification}><View style={s.notificationIcon}><Icon name="bag-handle-outline" size={22} /></View><View style={s.notificationCopy}><Label style={s.notificationTitle}>A little delivery, a little adventure.</Label><Label style={s.notificationSub}>{g.order.pickup.name} · {g.order.reward} coins</Label></View><Icon name="chevron-forward" size={17} /></Pressable>}
      {target && <View style={s.directions} testID="gps-directions"><View style={s.turn}><Icon name={targetNear ? 'flag' : nextDirection === 'north' ? 'arrow-up' : nextDirection === 'south' ? 'arrow-down' : nextDirection === 'west' ? 'arrow-back' : 'arrow-forward'} size={23} /></View><View style={s.directionCopy}><Label style={s.directionTitle}>{targetNear ? 'On the footpath. You’re here!' : route.length?`Head ${nextDirection} · ${Math.round(remaining)} m`:'Finding a safe route…'}</Label><Label style={s.directionSubtitle} numberOfLines={1}>{exploring?'EXPLORE':g.destination ? 'PIT STOP' : g.order?.status === 'accepted' ? 'PICK UP' : 'DELIVER'} · {target.name}</Label></View>{g.order?.status === 'accepted' ? <View style={s.step}><Icon name="timer-outline" size={14} /><Label testID="pickup-countdown" style={s.stepText}>{countdown(g.order.pickup_deadline, g.now)}</Label></View> : <Icon name={exploring?'compass-outline':g.destination ? 'construct-outline' : 'bag-check-outline'} size={20} />}</View>}
    </View>
    {ride.railNearby&&ride.rail.closed&&!near&&!nearService?<View testID="rail-gate-notice" style={[s.explore,{bottom:inset.bottom+222}]}><View style={s.railTitle}><Icon name="train-outline" size={20} color={c.coral}/><Label display style={s.exploreTitle}>Train crossing · {ride.rail.wait}s</Label></View><Label style={s.exploreNote}>Gates closed. Riders and traffic wait together.</Label></View>:!g.order && !nearService && !g.destination && <View pointerEvents="none" style={[s.explore, { bottom: inset.bottom + 222 }]}><Label display style={s.exploreTitle}>{ride.pushing ? 'One step at a time.' : region(ride.player) === 'Whispering Pines' ? 'The scenic way around.' : 'A little room to explore.'}</Label><Label style={s.exploreNote}>{ride.pushing ? 'Push to a service stop or call help from your phone.' : g.profile!.online ? 'No requests here yet. Visit other shops and streets.' : 'Open your phone to change your online status.'}</Label></View>}
    {near ? <View testID={g.order?.status === 'accepted' ? 'pickup-arrived' : 'dropoff-arrived'} style={[s.action, { bottom: inset.bottom + 222 }]}><Button testID="delivery-action-button" title={g.order?.status === 'accepted' ? 'PICK UP ORDER' : 'HAND OVER DELIVERY'} icon="bag-check-outline" loading={g.busy} onPress={g.interact} /></View> : nearService ? <View style={[s.action, { bottom: inset.bottom + 222 }]}><Button testID="open-service-stop-button" title={nearService.kind === 'garage' ? 'HOME SWEET GARAGE' : nearService.kind === 'fuel' ? 'FUEL & AIR STATION' : 'VISIT REPAIR SHOP'} icon={nearService.kind === 'garage' ? 'home-outline' : 'construct-outline'} onPress={() => g.openService(nearService)} /></View> : null}
    <View pointerEvents="box-none" style={[s.controls, { bottom: inset.bottom + 20 }]}><RideControls direction={ride.direction} disabled={g.busy || g.phone || !!g.panel || !!g.reward || g.profile!.dead} /><View style={s.phoneColumn}><View style={s.speed}><Label display style={s.speedValue}>{ride.speed}</Label><Label testID="movement-mode" style={s.speedUnit}>{ride.pushing ? 'PUSHING' : 'km/h'}</Label></View><Pressable testID="open-phone-button" accessibilityRole="button" accessibilityLabel="Open delivery phone" onPress={() => g.openPhone()} style={({ pressed }) => [s.phone, pressed && { transform: [{ scale: .94 }] }]}><Icon name="phone-portrait-outline" size={33} />{g.order && <View style={s.badge}><Label style={s.badgeText}>1</Label></View>}</Pressable><Label style={s.phoneLabel}>MY PHONE</Label></View></View>
    <View testID="rider-position" accessibilityLabel={`${Math.round(ride.player.x)},${Math.round(ride.player.y)}`} style={s.position}><Label style={s.positionText}>{Math.round(ride.player.x)}, {Math.round(ride.player.y)}</Label></View>
    {ride.railNearby&&<View testID="railway-telemetry" accessibilityLabel={JSON.stringify({closed:ride.rail.closed,blocked:ride.railBlocked,wait:ride.rail.wait,train:ride.rail.trainVisible,waitingVehicles:ride.vehicles.filter(v=>v.waiting&&Math.abs(v.y-3050)<400).length})} style={s.railTelemetry}><Label style={s.positionText}>{ride.rail.closed?'GATE CLOSED':'GATE OPEN'}</Label></View>}
  </View>;
}
const useStyles = makeStyles(c => ({
  railTitle:{flexDirection:'row',alignItems:'center',gap:8},railTelemetry:{position:'absolute',bottom:3,left:18},
  status: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 10, height: 44, backgroundColor: c.glass, borderRadius: 14, borderWidth: 1, borderColor: c.surface },
  page: { flex: 1, backgroundColor: c.grass, overflow: 'hidden' }, top: { position: 'absolute', left: 18, right: 18 }, topRow: { flexDirection: 'row', alignItems: 'center', gap: 9 }, home: { backgroundColor: c.glass, borderWidth: 1.5, borderColor: c.surface, width: 43 },
  weather: { flexDirection: 'row', flex: 1, height: 44, alignItems: 'center', justifyContent: 'center', gap: 7, borderRadius: 15, backgroundColor: c.glass, borderWidth: 1.5, borderColor: c.surface }, clock: { fontSize: 13, fontWeight: '800' }, smallDivider: { height: 14, width: 1, backgroundColor: c.border }, weatherLabel: { fontSize: 10, textTransform: 'capitalize' }, money: { backgroundColor: c.glass, borderRadius: 14, paddingHorizontal: 13, height: 44, justifyContent: 'center', borderWidth: 1.5, borderColor: c.surface },
  mapRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginTop: 13 }, map: { backgroundColor: c.glass, padding: 5, width: 114, borderRadius: 15, borderWidth: 1.5, borderColor: c.surface, overflow: 'hidden' }, mapWindow: { borderRadius: 10, overflow: 'hidden' }, mapLabel: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 5, paddingBottom: 2 }, mapText: { fontSize: 6, letterSpacing: .25, fontWeight: '800', flexShrink: 1 }, rightTop: { alignItems: 'flex-end', gap: 9 }, onlineActive: { backgroundColor: c.mint, borderColor: c.teal }, onlineDot: { height: 6, width: 6, borderRadius: 5 }, onlineText: { fontSize: 8, fontWeight: '800', letterSpacing: .4 },
  notification: { flexDirection: 'row', alignItems: 'center', padding: 12, gap: 10, marginTop: 14, borderRadius: 16, backgroundColor: c.glass, borderWidth: 1.5, borderColor: c.onSurface, borderBottomWidth: 3 }, notificationIcon: { width: 36, height: 36, backgroundColor: c.brand, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, notificationCopy: { flex: 1 }, notificationTitle: { fontSize: 11, fontWeight: '800' }, notificationSub: { fontSize: 10, marginTop: 3, color: c.muted },
  directions: { flexDirection: 'row', alignItems: 'center', padding: 11, gap: 10, marginTop: 14, borderRadius: 15, backgroundColor: c.glass, borderWidth: 1.5, borderColor: c.onSurface }, turn: { width: 39, height: 39, borderRadius: 11, backgroundColor: c.brand, alignItems: 'center', justifyContent: 'center' }, directionCopy: { flex: 1 }, directionTitle: { fontSize: 14, fontWeight: '800' }, directionSubtitle: { fontSize: 8.5, marginTop: 4, letterSpacing: .3, color: c.teal }, step: { backgroundColor: c.surfaceTertiary, borderRadius: 8, padding: 7 }, stepText: { fontSize: 10, fontWeight: '800' },
  controls: { position: 'absolute', left: 22, right: 25, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' }, phoneColumn: { alignItems: 'center' }, phone: { width: 74, height: 74, borderRadius: 25, backgroundColor: c.brand, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderBottomWidth: 5, borderColor: c.onSurface }, badge: { position: 'absolute', right: -3, top: -7, width: 22, height: 22, borderRadius: 11, backgroundColor: c.coral, borderWidth: 2, borderColor: c.surface, alignItems: 'center', justifyContent: 'center' }, badgeText: { color: c.surfaceSecondary, fontSize: 11, fontWeight: '800' }, phoneLabel: { fontSize: 8, letterSpacing: 1.7, backgroundColor: c.glass, paddingVertical: 3, paddingHorizontal: 8, marginTop: 8, borderRadius: 5, fontWeight: '800' },
  speed: { alignItems: 'center', marginBottom: 13, width: 52, height: 49, borderRadius: 12, backgroundColor: c.glass, justifyContent: 'center' }, speedValue: { fontSize: 23, lineHeight: 25 }, speedUnit: { fontSize: 8, color: c.muted },
  explore: { position: 'absolute', alignSelf: 'center', backgroundColor: c.glass, borderRadius: 16, paddingVertical: 12, paddingHorizontal: 18, alignItems: 'center' }, exploreTitle: { fontSize: 19 }, exploreNote: { fontSize: 10, marginTop: 4, color: c.muted }, action: { position: 'absolute', left: 24, right: 24 }, position: { position: 'absolute', bottom: 3, alignSelf: 'center' }, positionText: { fontSize: 7, color: c.onSurface, opacity: .5 },
}));